# 优化器的配置文件
base_config:
  optim_type: AdamW
  kwargs: |
    {
      "lr": 0.00006,
      "weight_decay": 0.01,
      "betas": (0.9, 0.999)
    }
  


parameters:
    # key(block, block, norm)自定义
    # default: decay_mult=1, lr_mult=1
    # left必须位于第一位，表示剩余的参数，可以更改内部属性中decay_mult和lr_mult, regex_expr不起作用
  - left:
      regex_expr: none
      decay_mult: 0
      lr_mult: 1
  - block:
      regex_expr: ^encoder\.stages\.[0-9]\.blocks.*$
      decay_mult: 0
      lr_mult: 1
  - norm:
      regex_expr: ^encoder\.stages\.[0-9]\.norm.*$
      decay_mult: 0
      lr_mult: 1
  - head:
      regex_expr: ^decoder.*$
      decay_mult: 1
      lr_mult: 10